---
title: "NLP Project Report"
author: "Najada Feimi, Elnaz Khaveh, Hamed Vaheb"
date: "12/29/2022"
output:
  html_document:
    number_sections: yes
    toc: yes
    code_folding: hide
    theme: readable
    highlight: haddock
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

# **Import Libraries**

```{r message = FALSE, warning = FALSE}
library(knitr)
library(dplyr)
library(ggplot2)
library(broom)
library(janitor)
library(renv)
library(purrr)
library(tm)
library(SnowballC)
library(RColorBrewer)
library(ggplot2)
library(wordcloud)
library(biclust)
library(cluster)
library(igraph)
library(fpc)
#packages <- c("tm", "SnowballCC", "RColorBrewer", "ggplot2", "wordcloud", "biclust", "cluster", "igraph", "fpc", "knitr", "dplyr", "broom", "janitor", "renv", "purrr")
#install.packages(packages, dependencies = TRUE)

```

# **Introduction**

## **Describe Dataset**

## **Goal and Procedure**

```{r}
df <- read.csv("https://raw.githubusercontent.com/berserkhmdvhb/MADS-NLP/main/data/presidents-speech.csv")
```

```{r}
df |> dplyr::glimpse()
```

```{r}
df |> summary()
```

```{r}
#presidents <- df[["president"]]|> unique() |>as.list()



for(i in 1:nrow(df)) {       # for-loop over rows
  df_i <- df[i, ]
  name <- df_i$president
  year <- df_i$year
  text <- df_i$content
  file_name <- paste(as.character(year), 
                     as.character(name), 
                     sep="-")
  file_name <- paste(file_name, ".txt", 
                     sep="")
  loc <- paste("/home/hamed/Documents/R/MADS-NLP/data/texts/", file_name, sep="")
  #write.table(text,loc)
}  
  
```

```{r}
loc <- "/home/hamed/Documents/R/MADS-NLP/data/texts"
docs <- VCorpus(DirSource(loc)) 
summary(docs) 
```

```{r}
inspect(docs[1])
```

```{r}
writeLines(as.character(docs[1]))
```

# Preprocessing

**Remove punctuation:**
```{r}
docs <- tm_map(docs,removePunctuation)   
# writeLines(as.character(docs[1])) # Check to see if it worked.
    # The 'writeLines()' function is commented out to save space.
```


**Remove special characters**

```{r}
for (j in seq(docs)) {
    docs[[j]] <- gsub("/", " ", docs[[j]])
    docs[[j]] <- gsub("@", " ", docs[[j]])
    docs[[j]] <- gsub("\\|", " ", docs[[j]])
    docs[[j]] <- gsub("\u2028", " ", docs[[j]])  # This is an ascii character that did not translate, so it had to be removed.
}
# writeLines(as.character(docs[1])) # You can check a document (in this case
# the first) to see if it worked.
```

**Remove special characters**
  